# This file is a template, and might need editing before it works on your project.
variables:
  REPO_NAME: /go/src/gitlab.com/waldirborbajr/nfeloader

before_script:
  - mkdir -p $(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $REPO_NAME
  - cd $REPO_NAME

stages:
  - test
  - build
  - release

.golang_default: &golang_default
  image: golang:latest

.docker_default: &docker_default
  image: docker:latest

test:
  <<: *golang_default
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

build:
  <<: *golang_default
  stage: build
  dependencies:
    - test
  script:
    - go build -race -a -installsuffix cgo -ldflags "-s -w" -v -o
      $CI_PROJECT_DIR/nfeloader

  artifacts:
    paths:
      - nfeloader
    expire_in: 1 hour

release:
  <<: *docker_default
  stage: release
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker login -u $DOCKER_REPO -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_REPO/$DOCKER_IMAGE:$IMG_TAG -f ./docker/Dockerfile
      .
    - docker push $DOCKER_REPO/$DOCKER_IMAGE:$IMG_TAG
