project_name: nfeloader

before:
  hooks:
    - go mod tidy

dockers:
- image_templates: ["ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/waldirborbajr/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/waldirborbajr/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
# - use: buildx
#   goos: linux
#   goarch: arm64
#   image_templates:
#   - waldirborbajr/nfeloader:{{ .Tag }}-arm64
#   build_flag_templates:
#   - "--build-arg=APPVERSION={{.ShortCommit}}"
#   - "--platform=linux/arm64"
#   - "--label=org.opencontainers.image.created={{.Date}}"
#   - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#   - "--label=org.opencontainers.image.version={{.Version}}"
# - use: buildx
#   dockerfile: ./docker-prod/Dockerfile
#   goos: linux
#   goarch: amd64
#   image_templates:
#   - waldirborbajr/nfeloader-image:{{ .Tag }}-amd64
#   # extra_files:
#   # - envoy/
#   build_flag_templates:
#   - "--build-arg=APPVERSION={{.ShortCommit}}"
#   - "--platform=linux/amd64"
#   - "--label=org.opencontainers.image.created={{.Date}}"
#   - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#   - "--label=org.opencontainers.image.version={{.Version}}"
# - use: buildx
#   dockerfile: ./docker-prod/Dockerfile
#   goos: linux
#   goarch: arm64
#   image_templates:
#   - waldirborbajr/nfeloader-image:{{ .Tag }}-arm64
#   extra_files:
#   - envoy/
#   build_flag_templates:
#   - "--build-arg=APPVERSION={{.ShortCommit}}"
#   - "--platform=linux/arm64"
#   - "--label=org.opencontainers.image.created={{.Date}}"
#   - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#   - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
- name_template: ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}-amd64
- name_template: ghcr.io/waldirborbajr/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}-amd64

  # - waldirborbajr/nfeloader:{{.Tag}}-amd64
  # - waldirborbajr/nfeloader:{{.Tag}}-arm64
# - name_template: waldirborbajr/nfeloader-image:latest
#   image_templates:
#   - waldirborbajr/nfeloader-image:{{.Tag}}-amd64
#   - waldirborbajr/nfeloader-image:{{.Tag}}-arm64
# - name_template: waldirborbajr/nfeloader:{{.Tag}}
#   image_templates:
#   - waldirborbajr/nfeloader:{{.Tag}}-amd64
#   - waldirborbajr/nfeloader:{{.Tag}}-arm64
# - name_template: waldirborbajr/nfeloader-image:{{.Tag}}
#   image_templates:
#   - waldirborbajr/nfeloader-image:{{.Tag}}-amd64
#   - waldirborbajr/nfeloader-image:{{.Tag}}-arm64

builds:
  - main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/waldirborbajr/nfeloader/internal/config.Verzion={{.Version}}
      - -X github.com/waldirborbajr/nfeloader/internal/config.Revizion={{.ShortCommit}}
      - -X github.com/waldirborbajr/nfeloader/internal/config.Commit={{ .Commit }}
      - -X github.com/waldirborbajr/nfeloader/internal/config.Date={{ .CommitDate }}
      - -X github.com/waldirborbajr/nfeloader/internal/config.BuiltBy=goreleaser

# checksum:
#   name_template: 'checksums.txt'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*(feat|fix)\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
      freebsd: FreeBSD
      windows: Windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: license*
      - src: LICENSE*
      - src: readme*
      - src: README*
      - src: changelog*
      - src: CHANGELOG*
    wrap_in_directory: true

release:
  prerelease: auto
  footer: |
    ## Binary Release
    **Full Changelog**: https://github.com/waldirborbajr/nfeloader/compare/{{ .PreviousTag }}...{{ .Tag }}
    ---
    _Released with [GoReleaser](https://goreleaser.com/)!_

    ## Docker Images
    - `waldirborbajr/nfeloader:latest`
    - `waldirborbajr/nfeloader:{{ .Tag }}`
    - `waldirborbajr/nfeloader-image:latest`
    - `waldirborbajr/nfeloader-image:{{ .Tag }}`
