project_name: nfeloader

env:
  - GIT_BRANCH='main'

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./cmd/cli/main.go
    binary: nfeloader

    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags '-static'
      - -X github.com/waldirborbajr/nfeloader/internal/version.Version={{ .Version }}
      - -X github.com/waldirborbajr/nfeloader/internal/version.GitCommit={{ .ShortCommit }}
      - -X github.com/waldirborbajr/nfeloader/internal/version.GitTag={{ .Tag }}
      - -X github.com/waldirborbajr/nfeloader/internal/version.GitSummary={{ .Summary }}
      - -X github.com/waldirborbajr/nfeloader/internal/version.BuildDate={{ .Date }}

    env:
      - CGO_ENABLED=0

    # goos: [ 'darwin', 'linux', 'freebsd', 'netbsd', 'dragonfly', 'openbsd', 'windows' ] # Dynamic
    # goarch: [ '386', 'amd64', 'mips', 'mips64', 'mips64le', 'mipsle', 'ppc64le', 'arm', 'arm64', 's390x' ] # Dynamic
    # goarm: [ '5', '6', '7' ] # Dynamic
    # gomips: [ 'hardfloat', 'softfloat' ] # Dynamic

    goos: ['linux', 'darwin','windows','freebsd']
    goarch: ['amd64','arm64']

    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
      - goos: openbsd
        goarch: arm
      - goos: netbsd
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: netbsd
        goarch: arm
      - goos: solaris
        goarch: arm

    mod_timestamp: '{{ .CommitTimestamp }}'
    skip: false

  - id: api
    main: ./cmd/api/main.go
    binary: nfeloader-api

    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags '-static'
      - -X github.com/waldirborbajr/nfeloader/internal/version.Version={{ .Version }}
      - -X github.com/waldirborbajr/nfeloader/internal/version.GitCommit={{ .ShortCommit }}
      - -X github.com/waldirborbajr/nfeloader/internal/version.GitTag={{ .Tag }}
      - -X github.com/waldirborbajr/nfeloader/internal/version.GitSummary={{ .Summary }}
      - -X github.com/waldirborbajr/nfeloader/internal/version.BuildDate={{ .Date }}

    env:
      - CGO_ENABLED=0

    targets:
      - linux_amd64

    mod_timestamp: '{{ .CommitTimestamp }}'
    # skip: false

universal_binaries:
- replace: true

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*(feat|fix)\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

archives:
  - builds: [ cli ]
  # - id: cli
    builds:
      - cli
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true

    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
      freebsd: FreeBSD
      windows: Windows

    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

    files:
      - src: license*
      - src: LICENSE*
      - src: readme*
      - src: README*
      - src: changelog*
      - src: CHANGELOG*

release:
  github:
  prerelease: auto
  ids:
    - cli

  footer: |
    ## Binary Release

    **Full Changelog**: https://github.com/waldirborbajr/nfeloader/compare/{{ .PreviousTag }}...{{ .Tag }}

    _Released with [GoReleaser](https://goreleaser.com/)!_

    ---

    ## Docker Images

    - ghcr.io/waldirborbajr/nfeloader:latest
    - 'ghcr.io/waldirborbajr/nfeloader:{{ .Version }}'

dockers:
- image_templates:
  - 'waldirborbajr/{{ .ProjectName }}:{{ .Version }}-amd64'
  - 'ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}-amd64'
  # extra_files:
  #   - nfeloader-api
  use: buildx
  goos: linux
  goarch: amd64
  dockerfile: Dockerfile
  build_flag_templates:
  - --pull
  - --label=io.artifacthub.package.maintainers=[{\"name\":\"Waldir Borba Junior (c)\",\"email\":\"wborbajr@gmail.com\"}]
  - --label=org.opencontainers.image.description=NFe Loader - from XML to MySQL
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.name={{ .ProjectName }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.source={{ .GitURL }}
  - --label=org.opencontainers.image.url=https://github.com/waldirborbajr/{{ .ProjectName }}
  - --platform=linux/amd64

- image_templates:
  - 'waldirborbajr/{{ .ProjectName }}:{{ .Version }}-arm64'
  - 'ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}-arm64'
  # extra_files:
  #   - nfeloader-api
  use: buildx
  goos: linux
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - --pull
  - --label=io.artifacthub.package.maintainers=[{\"name\":\"Waldir Borba Junior (c)\",\"email\":\"wborbajr@gmail.com\"}]
  - --label=org.opencontainers.image.description=NFe Loader - from XML to MySQL
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.name={{ .ProjectName }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.source={{ .GitURL }}
  - --label=org.opencontainers.image.url=https://github.com/waldirborbajr/{{ .ProjectName }}
  - --platform=linux/arm64

docker_manifests:
- name_template: ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}-arm64

- name_template: ghcr.io/waldirborbajr/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/waldirborbajr/{{ .ProjectName }}:{{ .Version }}-arm64
