[files]
extend-exclude = [
  "/internal/telegram/telegram.go",
  "/internal/entity/nfeproc.go",
  "/internal/repository/nfeproc_mysql.go",
  "/internal/services/quotation.go",
  "/docker-dev/entrypoint/database/nfeloader.sql",
  "/cmd/api/certs/",
  "/docker-prod/Dockerfile",
]
