/* 4:52:56 PM OMNI-VPN ICMS_NATAL */ ALTER TABLE `nfe` ADD `nfref_refNFe` VARCHAR(100)  NULL  DEFAULT NULL  COMMENT 'nfref_refNFe'  AFTER `ide_verProc`;
/* 4:53:58 PM OMNI-VPN ICMS_NATAL */ ALTER TABLE `nfe` ADD `transp_pesoL` VARCHAR(100)  NULL  DEFAULT NULL  COMMENT 'transp_pesoL'  AFTER `transp_nVol`;
/* 4:54:51 PM OMNI-VPN ICMS_NATAL */ ALTER TABLE `nfe` ADD `transp_pesoB` VARCHAR(100)  NULL  DEFAULT NULL  COMMENT 'transp_pesoB'  AFTER `transp_pesoL`;
/* 4:55:20 PM OMNI-VPN ICMS_NATAL */ ALTER TABLE `nfedetalhe` CHANGE `id` `id` BIGINT(11)  UNSIGNED  NOT NULL  AUTO_INCREMENT;
