name: Typo Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: typos-action
      uses: crate-ci/typos@master

    - name: Trigger CodeQL
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        event-type: trigger-lint
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
