name: Build & Test

on:
  push:
    branches:
      - '**'
    # tags:
    #   - v*
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    needs: [lint]
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:

    - name: "Setup Git Project"
      uses: actions/checkout@v3

    - name: "Setup Go Env"
      uses: actions/setup-go@v3
      with:
        cache: true
        go-version: ">=1.19"

    - name: "Check Go Dependencies"
      run: go mod tidy

    - name: "Check Go Tests"
      run: go test -v -cover -race -timeout 60s ./...

    - name: "Check Go Formatting"
      run: |
        test -z $(gofmt -l -s .)

  build:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ">=1.19"

    - name: Build
      run: go build -v ./...
