name: Release Binary

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

# permissions:
#   contents: read
#   id-token: write
#   packages: write

jobs:
  image-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - run: git fetch --force --tags

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
          cache: true
      - run: go test -v -cover -race -timeout 60s ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          args: release --rm-dist
          # workdir: cmd/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup Qemu"
        uses: docker/setup-qemu-action@v2

      - name: "Setup BuildX"
        uses: docker/setup-buildx-action@v2

      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
