name: Release Binary

on:
  push:
    tags:
      - 'v*'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

# permissions:
#   contents: write
#   id-token: write
#   packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
      # id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - run: git fetch --force --tags

      - name: "Setup Qemu"
        uses: docker/setup-qemu-action@v2

      - name: "Seyup BuildX"
        uses: docker/setup-buildx-action@v2

      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
          cache: true
      - run: go test -v -cover -race -timeout 60s ./...
      # - run: go test -v ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          args: release --rm-dist
          # workdir: cmd/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

