name: Build & Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

# permissions:
#   contents: read
#   id-token: write
#   packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - run: git fetch --force --tags

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
          cache: true
      - run: go test -v -cover -race -timeout 60s ./...

      - name: "Compile the source"
        id: compile
        if: github.ref == 'refs/heads/main'
        uses: goreleaser/goreleaser-action@v3
        with:
          args: build --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Release a new version"
        uses: goreleaser/goreleaser-action@v3
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          args: release --rm-dist --parallelism 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup Qemu"
        uses: docker/setup-qemu-action@v2

      - name: "Setup BuildX"
        uses: docker/setup-buildx-action@v2

      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
