name: Typo Check

on: [workflow_call]
  # push:
  #   branches:
  #     - '**'
  # pull_request:
  #   branches:
  #     - '**'

jobs:
  typocheck:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: typos-action
      uses: crate-ci/typos@master

